### PR TITLE
Add option '--long-idle' for server

### PR DESCRIPTION
**Pull request by lixingcong**
Restore the default behavior handling timeout, make an option to enable long idle connections.

这个[issue 2078](https://github.com/shadowsocks/shadowsocks-android/issues/2078)描述的是超长连接，如600s会被关闭，且ss-android端不可配置，然后@MyGod 的 https://github.com/shadowsocks/shadowsocks-libev/pull/2421 修改实现了长连接，避免了FCM之类长连接的断开。

实测在中国移动手机环境下，使用ss-android，然后手动断开4G网络，保持ss-android运行，服务器这个长连接会一直存在，数天后仍然未被ss-server进程关闭，这种无意义的长连接占用了系统资源。况且中国移动存在NAT防火墙，会掐断某些NAT连接不会主动通知ss-server端，ss-server会一直保留这个连接。

ss-server端的Linux中大量的长连接，须要还原最初的libev的timeout定时器机制清理。

实现保持长连接，跟ss最初设计初衷“避免长链接特征”来定期清理不活动连接是矛盾的。既要长连接，又要不被防火墙发现，实在是不可兼得。最好是由用户设定是否采用长连接。

### CODE REVIEW

**Comment by Mygod** [comment]
I don't consider long idle connections as a very useful feature.

**Comment by madeye** [comment]
The problem described in this pull request indeed exists. 

I think we can have a minimal connection timeout value like `36000` as a trade-off here.

**Comment by Mygod** [comment]
These "resources" should only concern large scale servers imo. I don't see
any problems here on my side.

**Comment by madeye** [comment]
In a production environment, the TCP idle timeout is still quite important.

I think the best trade-off is setting a very large timeout value if "resource" is not problem.

**Comment by Mygod** [comment]
Oh sorry I misunderstood. This seems like a good idea. Let us shorten timeout to 8000 seconds instead, respecting that of [TCP keepalive](http://man7.org/linux/man-pages/man7/tcp.7.html) (although I don't think shadowsocks supports TCP keepalive).

**Pull request merged**
