### PR TITLE
优化漫画人规则

### PR DESCRIPTION
**Pull request by thelastfantasy**

### CODE REVIEW

**Comment by madeye** [comment]
I suggest to add it to your custom rules in the shadowsocks client. Obviously, it couldn't be part of GFWList.

**Comment by thelastfantasy** [comment]
ok I'll close this pull request, by the way can you tell me where is the documentation of the .ACL file.
I added a rule
```
[bypass_all]
(^|\w+\.(\w+\-?)+)\.cdndm5?.com(\n|$)
```
but it do not work, the regex is tested ok.

**Comment by Mygod** [comment]
There isn't any documentations last time I checked. You can read acl.c to find out it's implementation details.

**Comment by madeye** [comment]
Before any proxy urls, please add `[proxy_list]`. In your case, it'd be:

```
[bypass_all]
[proxy_list]
(^|\w+\.(\w+\-?)+)\.cdndm5?.com(\n|$)
```

No docs for ACL yet. But all the example usages can be found here:

https://github.com/shadowsocks/shadowsocks-libev/tree/master/acl

**Comment by madeye** [comment]
BTW, your regex seems incorrect.

https://www.debuggex.com/r/1J9FtNRTXj_dgE3X

**Comment by thelastfantasy** [comment]
```
manhua1023.61-174-50-98.cdndm5.com
by98.tel.cdndm.com
manhua1023.104-250-150-10.cdndm5.com
```
I want to match urls like this but not www.cdndm5.com, but there are still some problems in the regex.

**Pull request closed without merging**
