### PR TITLE
Enable TCP keep-alive feature for remote connections

### PR DESCRIPTION
**Pull request by Chion82**
When an OpenWRT router is connected to the Internet via multiple NAT, it's likely that the TCP connections to the remote Shadowsocks server will fail after a few minutes of inactivation without the clients being noticed.  A typical case is that when a LAN user browses google.com for the first time and then browse it again a few minutes later, the browser will reuse the previously established connection which is no longer available and not closed by the router(not even a broken pipe signal is triggered), resulting in connection timeout and the browser reconnecting. To make the remote connections live longer and automatically close broken connections, enabling TCP keep-alive does the trick. I have tested this fix and it works pretty well.

### CODE REVIEW

**Comment by madeye** [comment]
You should increase the timeout number on both server and client. A recommended number is 600 if you have any long TCP connection.

Never use this trick, as shadowsocks is designed to close connections aggressively to avoid DOS attack.

**Comment by Chion82** [comment]
@madeye My point is that the TCP connection will be implicitly closed by **NAT routers from the ISP** while both server and client don't notice(At this time, ss-redir still thinks the remote connection is usable and send data without catching a broken pipe exception). It isn't the server or the client that close the connection aggressively due to timeout so increasing the number in the settings doesn't work. Is there any better workaround to solve this problem?

**Comment by madeye** [comment]
Sounds interesting. Could you also add this to ss-local and ss-tunnel? I'd like to try them locally.

**Comment by madeye** [comment]
Also, make sure they can be built in MinGW: https://github.com/joyent/libuv/issues/228

**Comment by Chion82** [comment]
@madeye Thanks. I will try modifying ss-local in the same way later. ss-tunnel uses UDP and doesn't need this fix, I think. :)

**Comment by Chion82** [comment]
After many tests it looks like this trick works just little but my bad network status should be to blame for the instability.

**Comment by Chion82** [comment]
Again, I test for many times and I'm sure that this trick works. Even though I switched to a ShdowSocks server with fast, stable connection, the Telecom NAT routers still drop inactive TCP connections leaving ss-redir not noticed. My test is as follows:
* Using the original version of ss-redir: 
```
$ nc www.google.com 80
GET / HTTP/1.1

HTTP/1.1 302 FOUND
(...normal response from google...)
(...wait for 3~5 minutes...)
GET / HTTP/1.1

(no response at this time, but nc doesn't exit)
```
* Using my modified version of ss-redir:
```
$ nc www.google.com 80
GET / HTTP/1.1

HTTP/1.1 302 FOUND
(...normal response from google...)
(...wait for 3~5 minutes...)
(connection closed by ss-redir and nc exits)
$
```
It's likely that this issue only happens on ss-redir. ss-local and ss-tunnel are fine.
BTW, not all ISP NAT routers drop inactive connections in such short period of time, so not everyone can recreate this problem.

**Comment by madeye** [comment]
Let's merge this patch for now and see what will happen.

**Comment by meliuyue** [comment]
可以把超时设置的短一点，即使NAT导致连接失效也会在超时以后重新建立连接吧？

**Comment by Chion82** [comment]
@meliuyue 主要问题在于之前的ss-redir不能主动判断NAT路由器是否已经抛弃连接。send()超时后ss会直接关闭本地客户端连接。ss的超时设置指的是send()或recv()阻塞方法的超时，而不是维护非活动TCP长连接的时间。如果ss通过TCP_KEEPALIVE实现自动检测并主动关闭失效连接，能使得客户端应用在复用无效TCP连接传输数据之前就重新建立连接，比如能够避免浏览器在复用TCP连接访问网站时报Empty response from server错误。
当然这只是我多次实验的结果，ss的源码我并没有完全读完，如有错误望指正。

**Pull request merged**
