### PR TITLE
Add --tcp-incoming-sndbuf and --tcp-outgoing-sndbuf which allow precise control over TCP send buffers.

### PR DESCRIPTION
**Pull request by notsure2**
- This is very useful in advanced scenarios such as ss-redir or chaining of shadowsocks servers 
  using TPROXY and ss-redir to another shadowsocks server. This allows avoiding bufferbloat-like 
  performance degradation due to default large buffers of OS.

### CODE REVIEW

**Review by madeye — APPROVED** [review]
LGTM.

**Comment by notsure2** [comment]
Hmmm reading the parameter from config seems not working, I'll check this again.

**Comment by notsure2** [comment]
Ok looks like I will implement this for receive buffers as well, I will update this pull request.

**Comment by notsure2** [comment]
Been using this for 10 hours with no issues. I have posted my notes on buffer tuning here: https://github.com/notsure2/linux-vpn-bridge

@madeye can we get a review and merge 👍

**Review by madeye — APPROVED** [review]

**Comment by dev4u** [comment]
真的有效果，我会继续观察。
希望更新配置文档，让更多人受益。

**Comment by debiansid** [comment]
> 真的有效果，我会继续观察。
> 希望更新配置文档，让更多人受益。

any examples?

**Comment by dev4u** [comment]
> > 真的有效果，我会继续观察。
> > 希望更新配置文档，让更多人受益。
> 
> any examples?

简单粗暴，移动网络下，4个参数设置为8k，固网下设置为16k。
客户端不要设置这四个参数，看视频会有减速的效果。

**Comment by dev4u** [comment]
> > 真的有效果，我会继续观察。
> > 希望更新配置文档，让更多人受益。
> 
> any examples?

简单粗暴，移动网络下，4个参数设置为8k，固网下设置为16k。
手机客户端不要设置这四个参数，看视频会有减速的效果。其他的客户端未作尝试。

**Pull request merged**
