### PR TITLE
"DynamicUser=true" makes "/etc/init.d/shadowsocks-libev start" fail.

### PR DESCRIPTION
**Pull request by abnerbob**
环境: 
Linux version 5.4.0-1040-gcp (buildd@lcy01-amd64-013) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #43-Ubuntu SMP Fri Mar 19 17:49:48 UTC 2021

执行这个 /etc/init.d/shadowsocks-libev start 不成功，发现这个参数DynamicUser=true注释掉后可以成功，并且没有什么影响。

感觉跟用户权限相关系。

服务的配置文件/etc/default/shadowsocks-libev中也给了USER=nobody GROUP=nogroup两个参数，所以在启动过程中动态分配用户，感觉意义不大。
重启服务器的需求比较少，一般都直接后台运行不管它。再者，反复重启的情况是异常~

### CODE REVIEW

**Comment by abnerbob** [comment]
| enviroment | Version   |
| ------- | ------------------ |
|ubuntu|7ubuntu1~20.04 -- 5.4.0-1040-gcp|
|shadowsocks (server)|  shadowsocks-libev/focal,now 3.3.4+ds-2 amd64|
| v2ray-plugin (server) |v2ray-plugin-linux-amd64-v1.3.1.tar.gz |

**Comment by abnerbob** [comment]
忘了贴log……
查看status，显示插件异常退出，很奇怪～

**Comment by aueu** [comment]
用了DynamicUser，就不应该以nobody去运行
实际上，DynamicUser是更推荐的做法

**Comment by manjuprajna** [comment]
@abnerbob why you have to use init.d instead of sytemd? use systemd never had such problem. if you have to use init.d, just # your .service file as you like. if without DynamicUser may cause problem when try to bind ports lower than 1024.

**Comment by abnerbob** [comment]
> 用了DynamicUser，就不应该以nobody去运行
> 实际上，DynamicUser是更推荐的做法

讲道理是应该用DynamicUser。虽然我不了解DynamicUser和nobody的差别带来的具体影响，也不太够深入了解systemd，但是确实会出错呢~大佬有什么好文章对服务这块有细致点的介绍吗？想学习下~

**Comment by abnerbob** [comment]
> @abnerbob why you have to use init.d instead of sytemd? use systemd never had such problem. if you have to use init.d, just # your .service file as you like. if without DynamicUser may cause problem when try to bind ports lower than 1024.

it did  cause problem while i didn't know the further reason.
```
root@google-tw-b-2:~# systemctl start  shadowsocks-libev.service
root@google-tw-b-2:~# systemctl status  shadowsocks-libev.service
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
     Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-05-12 22:51:58 CST; 2s ago
       Docs: man:shadowsocks-libev(8)
    Process: 61583 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255/EXCEPTION)
   Main PID: 61583 (code=exited, status=255/EXCEPTION)

May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: initializing ciphers... aes-256-gcm
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: tcp server listening at 127.0.0.1:38401
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: udp server listening at 0.0.0.0:443
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.3 linux/amd64)
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 A unified platform for anti-censorship.
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 443 > v2ray.com/core/transp>
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 ERROR: plugin service exit unexpectedly
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: error on terminating the plugin.
May 12 22:51:58 google-tw-b-2 systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/EXCEPTION
May 12 22:51:58 google-tw-b-2 systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.


root@google-tw-b-2:~# systemctl status  shadowsocks-libev.service >log.v2
root@google-tw-b-2:~# cat log.v2
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
     Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-05-12 22:51:58 CST; 3min 9s ago
       Docs: man:shadowsocks-libev(8)
    Process: 61583 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255/EXCEPTION)
   Main PID: 61583 (code=exited, status=255/EXCEPTION)

May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: initializing ciphers... aes-256-gcm
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: tcp server listening at 127.0.0.1:38401
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: udp server listening at 0.0.0.0:443
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.3 linux/amd64)
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 A unified platform for anti-censorship.
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 443 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:443 > v2ray.com/core/transport/internet/websocket: failed to listen TCP on0.0.0.0:443 > listen tcp 0.0.0.0:443: bind: permission denied
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 ERROR: plugin service exit unexpectedly
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: error on terminating the plugin.
May 12 22:51:58 google-tw-b-2 systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/EXCEPTION
May 12 22:51:58 google-tw-b-2 systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.



root@google-tw-b-2:~# cat /etc/shadowsocks-libev/config.json
{
    "server":"0.0.0.0",
    "mode":"tcp_and_udp",
    "server_port":443,
    "local_port":80,
    "password":"6#kk",
    "timeout":600,
    "method":"aes-256-gcm",
    "plugin":"/usr/bin/v2ray-plugin",
    "plugin_opts":"server;path=/;host=www.;mux=0;loglevel=debug"
}

root@google-tw-b-2:~# systemctl status  shadowsocks-libev.service
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
     Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-05-12 22:51:58 CST; 4min 5s ago
       Docs: man:shadowsocks-libev(8)
    Process: 61583 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255/EXCEPTION)
   Main PID: 61583 (code=exited, status=255/EXCEPTION)

May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: initializing ciphers... aes-256-gcm
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: tcp server listening at 127.0.0.1:38401
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: udp server listening at 0.0.0.0:443
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.3 linux/amd64)
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 A unified platform for anti-censorship.
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 443 > v2ray.com/core/transp>
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 ERROR: plugin service exit unexpectedly
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: error on terminating the plugin.
May 12 22:51:58 google-tw-b-2 systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/EXCEPTION
May 12 22:51:58 google-tw-b-2 systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.


root@google-tw-b-2:~# cat log.v2
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
     Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-05-12 22:51:58 CST; 3min 9s ago
       Docs: man:shadowsocks-libev(8)
    Process: 61583 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255/EXCEPTION)
   Main PID: 61583 (code=exited, status=255/EXCEPTION)

May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: initializing ciphers... aes-256-gcm
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: tcp server listening at 127.0.0.1:38401
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: udp server listening at 0.0.0.0:443
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.3 linux/amd64)
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 A unified platform for anti-censorship.
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 443 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:443 > v2ray.com/core/transport/internet/websocket: failed to listen TCP on0.0.0.0:443 > listen tcp 0.0.0.0:443: bind: permission denied
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 ERROR: plugin service exit unexpectedly
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: error on terminating the plugin.
May 12 22:51:58 google-tw-b-2 systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/EXCEPTION
May 12 22:51:58 google-tw-b-2 systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.
root@google-tw-b-2:~#
root@google-tw-b-2:~#
root@google-tw-b-2:~#
root@google-tw-b-2:~# cat log.v2
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
     Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-05-12 22:51:58 CST; 3min 9s ago
       Docs: man:shadowsocks-libev(8)
    Process: 61583 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255/EXCEPTION)
   Main PID: 61583 (code=exited, status=255/EXCEPTION)

May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: initializing ciphers... aes-256-gcm
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: tcp server listening at 127.0.0.1:38401
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: udp server listening at 0.0.0.0:443
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.3 linux/amd64)
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 A unified platform for anti-censorship.
May 12 22:51:58 google-tw-b-2 ss-server[61593]: 2021/05/12 22:51:58 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 443 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:443 > v2ray.com/core/transport/internet/websocket: failed to listen TCP on0.0.0.0:443 > listen tcp 0.0.0.0:443: bind: permission denied
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 ERROR: plugin service exit unexpectedly
May 12 22:51:58 google-tw-b-2 ss-server[61583]:  2021-05-12 22:51:58 INFO: error on terminating the plugin.
May 12 22:51:58 google-tw-b-2 systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/EXCEPTION
May 12 22:51:58 google-tw-b-2 systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.


root@google-tw-b-2:~# cat /etc/shadowsocks-libev/config.json
{
    "server":"0.0.0.0",
    "mode":"tcp_and_udp",
    "server_port":443,
    "local_port":80,
    "password":"6#kkR!!",
    "timeout":600,
    "method":"aes-256-gcm",
    "plugin":"/usr/bin/v2ray-plugin",
    "plugin_opts":"server;path=/;host=www.;mux=0;loglevel=debug"
}

root@google-tw-b-2:~# cat /lib/systemd/system/shadowsocks-libev.service
#  This file is part of shadowsocks-libev.
#
#  Shadowsocks-libev is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This file is default for Debian packaging. See also
#  /etc/default/shadowsocks-libev for environment variables.

[Unit]
Description=Shadowsocks-libev Default Server Service
Documentation=man:shadowsocks-libev(8)
After=network-online.target

[Service]
Type=simple
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
DynamicUser=true
EnvironmentFile=/etc/default/shadowsocks-libev
LimitNOFILE=32768
ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS

[Install]
WantedBy=multi-user.target




root@google-tw-b-2:~# vi /lib/systemd/system/shadowsocks-libev.service
root@google-tw-b-2:~# cat /lib/systemd/system/shadowsocks-libev.service
#  This file is part of shadowsocks-libev.
#
#  Shadowsocks-libev is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This file is default for Debian packaging. See also
#  /etc/default/shadowsocks-libev for environment variables.

[Unit]
Description=Shadowsocks-libev Default Server Service
Documentation=man:shadowsocks-libev(8)
After=network-online.target

[Service]
Type=simple
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
#DynamicUser=true
EnvironmentFile=/etc/default/shadowsocks-libev
LimitNOFILE=32768
ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS

[Install]
WantedBy=multi-user.target


root@google-tw-b-2:~# systemctl start shadowsocks-libev
Warning: The unit file, source configuration file or drop-ins of shadowsocks-libev.service changed on disk. Run 'systemctl daemon-reload' to reload units.
root@google-tw-b-2:~# systemctl daemon-reload
root@google-tw-b-2:~# systemctl start shadowsocks-libev
root@google-tw-b-2:~# systemctl status shadowsocks-libev
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
     Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-05-12 22:58:05 CST; 8s ago
       Docs: man:shadowsocks-libev(8)
   Main PID: 61820 (ss-server)
      Tasks: 9 (limit: 2374)
     Memory: 12.0M
     CGroup: /system.slice/shadowsocks-libev.service
             ├─61820 /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json
             └─61821 /usr/bin/v2ray-plugin

May 12 22:58:05 google-tw-b-2 ss-server[61820]:  2021-05-12 22:58:05 INFO: UDP relay enabled
May 12 22:58:05 google-tw-b-2 ss-server[61820]:  2021-05-12 22:58:05 INFO: initializing ciphers... aes-256-gcm
May 12 22:58:05 google-tw-b-2 ss-server[61820]:  2021-05-12 22:58:05 INFO: tcp server listening at 127.0.0.1:49581
May 12 22:58:05 google-tw-b-2 ss-server[61820]:  2021-05-12 22:58:05 INFO: udp server listening at 0.0.0.0:443
May 12 22:58:05 google-tw-b-2 ss-server[61820]:  2021-05-12 22:58:05 INFO: running from root user
May 12 22:58:06 google-tw-b-2 ss-server[61821]: 2021/05/12 22:58:06 V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.3 linux/amd64)
May 12 22:58:06 google-tw-b-2 ss-server[61821]: 2021/05/12 22:58:06 A unified platform for anti-censorship.
May 12 22:58:06 google-tw-b-2 ss-server[61821]: 2021/05/12 22:58:06 [Debug] v2ray.com/core/app/log: Logger started
May 12 22:58:06 google-tw-b-2 ss-server[61821]: 2021/05/12 22:58:06 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 0.0.0.0:443
May 12 22:58:06 google-tw-b-2 ss-server[61821]: 2021/05/12 22:58:06 [Warning] v2ray.com/core: V2Ray 4.23.2 started
```

**Comment by manjuprajna** [comment]
@abnerbob since you've modified the systemd service file, why still using init.d to start service?
systemctl enable ****.service && systemctl start ****.service, so simple.

**Comment by abnerbob** [comment]
> @abnerbob since you've modified the systemd service file, why still using init.d to start service?
> systemctl enable ****.service && systemctl start ****.service, so simple.

i had used systemctl, but there were still some errors as shown in log.

**Pull request merged**
