### PR TITLE
debian/shadowsocks-libev.{default,init,service}: Run service as non-root

### PR DESCRIPTION
**Pull request by rogers0**

### CODE REVIEW

**Comment by rogers0** [comment]
Previous PR didn't include libcap2-bin as Depends, which is fixed in this time.
I've already included this change in 2.6.2+ds-1 (debian sid) version.
No bug report so far.

Of course, you can hold for a while.

**Comment by madeye** [comment]
Thanks!

**Comment by madeye** [comment]
An additional note may be added to remind users granting permission to plugin's executable, if they are going to use [SIP003] plugin with this init scripts.

`setcap 'cap_net_bind_service=+ep' /path/to/plugin`

[SIP003]: https://github.com/shadowsocks/shadowsocks-org/issues/28

**Comment by rogers0** [comment]
Thanks for the remind!
I think it's a bug need to fix, just adding a new entry in:
- debian/shadowsocks-libev.postinst

**Comment by rogers0** [comment]
Sorry, I thought the plugin was already done and included in the src/.
Now I understand the plugin is a separated program.
If the plugin is required to bind a port to listen, it need the setcap command you mentioned.

**Pull request merged**
