### PR TITLE
Feature/add cmake doc

### PR DESCRIPTION
**Pull request by wenerme**
Build doc-html,doc-man, controlled by WITH_DOC_MAN, WITH_DOC_HTML, detect required xmlto and asciidoc

install html to doc/html, any problem with this ?

```bash
cd build
# Test install
cmake -DCMAKE_INSTALL_PREFIX:PATH=$PWD/out ..
make install
```

### CODE REVIEW

**Comment by wenerme** [comment]
Currently, we still install shared and static libs, is this ok or not ?

**Comment by madeye** [comment]
We'd better not install any third-party library, to avoid any possible conflict with system libraries.

**Comment by wenerme** [comment]
Yes, I install libshadowsocks-libev only.

But for libshadowsocks-libev, should we install shared or both ?

**Comment by wenerme** [comment]
BTW, I forget to install header too, I will install shadowsocks.h

**Comment by madeye** [comment]
It doesn't matter. Let's just install both of them.

**Pull request merged**
