### PR TITLE
A few commit recommend for Debian uploading

### PR DESCRIPTION
**Pull request by rogers0**
Here're a few commits with small changes which suitable for Debian packaging.
Hope it can be merged soon. Thanks for your consideration!

### CODE REVIEW

**Comment by hosiet** [comment]
Could you confirm that hardening flag is actually working? src/Makefile.am
seems has had those AM_CFLAGS overridden.

**Comment by hosiet** [comment]
Plus, setting debian/source/format to `3.0 (quilt)` will disable the simple packaging guide in `README.md`.

**Comment by rogers0** [comment]
> Could you confirm that hardening flag is actually working? 

I did a "diff" for build log, and found "-fPIE" option added after the hardening setting

**Comment by rogers0** [comment]
> Plus, setting debian/source/format to 3.0 (quilt) will disable the simple packaging guide in README.md

May I know what would break exactly?
According to the guide below, it should be set like that after squeeze.
Ref: https://www.debian.org/doc/manuals/maint-guide/dother.en.html#sourcef

**Pull request merged**
