### PR TITLE
Revert "Revert "Update README.md (#1111)""

### PR DESCRIPTION
**Pull request by ky0ncheng**
Reverts shadowsocks/shadowsocks-libev#1115

### CODE REVIEW

**Comment by rogers0** [comment]
Why do you insist on this change?
pkg src:shadowsocks in debian is a python implementation, though shares the same protocol with this one.

**Comment by ky0ncheng** [comment]
@rogers0 

➜ shadowsocks-libev git:(master) ✗ apt-get install shadowsocks
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
python-m2crypto python-pkg-resources
Suggested packages:
python-setuptools
The following NEW packages will be installed:
python-m2crypto python-pkg-resources shadowsocks
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 450 kB of archives.
After this operation, 2,361 kB of additional disk space will be used.
Do you want to continue? [Y/n]

➜ shadowsocks-libev git:(master) ✗ apt-get install shadowsocks-libev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package shadowsocks-libev

This is your package name problem.

or rename python version to shadowsocks-python for identify.

**Comment by rogers0** [comment]
@ky0ncheng What Debian version are you using?
I guess you need to read:
- https://github.com/shadowsocks/shadowsocks-libev#install-from-repository

**Comment by ky0ncheng** [comment]
@rogers0 

Separation or unity, I guess you need to understand, rename package can slove all installation problem.

**Comment by rogers0** [comment]
@ky0ncheng I don't see any installation issue. If you have, please report.
For the naming, I just follow upstream's decision.

**Comment by wongsyrone** [comment]
This doesn't make any sense.

**Comment by ky0ncheng** [comment]
@rogers0 Upstream's no decision, this problem existed forever.

https://github.com/shadowsocks/shadowsocks-libev/issues/162

You need google.

@wongsyrone hehe.

**Pull request closed without merging**
