### PR TITLE
Switch random generator to libsodium's

### PR DESCRIPTION
**Pull request by wongsyrone**
to get rid of self written code and make it clean.

Official doc: https://download.libsodium.org/doc/generating_random_data/

Signed-off-by: Syrone Wong <wong.syrone@gmail.com>

### CODE REVIEW

**Comment by wongsyrone** [comment]
I suggest upgrading internal libsodium to latest release: 1.0.11

**Comment by madeye** [comment]
The part we're using hasn't changed for months: 

https://github.com/jedisct1/libsodium/tree/68564326e1e9dc57ef03746f85734232d20ca6fb/src/libsodium/crypto_stream

**Comment by wongsyrone** [comment]
This one is a big deal.

> sodium_init() is now thread-safe, and can be safely called multiple times.

**Comment by madeye** [comment]
Not a big deal for shadowsocks-libev, which is "carefully" designed to be a single-thread program...

**Comment by wongsyrone** [comment]
OK. We are safe now.

**Pull request merged**
