### PR TITLE
Show encryption library used in the help message

### PR DESCRIPTION
**Pull request by rampageX**
ss-local -h

shadowsocks-libev 2.5.3 **with mbed TLS 2.2.1**

### CODE REVIEW

**Comment by wongsyrone** [comment]
Does this really make sense?

**Comment by wongsyrone** [comment]
In general, if you build for OpenWrt/LEDE, package name contains crypto library name.

**Comment by hosiet** [comment]
It is not the problem of package name. The problem is that the branch commits are dirty.

**Comment by madeye** [comment]
Please clean up your pull request first.

**Comment by wongsyrone** [comment]
They can be squashed into one commit if madeye wants to merge it.

**Pull request closed without merging**
