### PR TITLE
Remove sniparser

### LINKED ISSUE #2627: I consider sniparser harmful
SNI parser was introduced in #809. While this feature might be useful for routers, I argue that this is the **wrong** way to tackle the DNS rerouting problem -- an ideal solution should be setting up a DNS server/relay, like `LocalDnsServer` in shadowsocks-android. Just a quick comparison...

Advantage of using sniparser:

1. No need to set up a DNS server. (though if you have gone through the trouble of getting shadowsocks-libev on your router, you might as well just do the extra step)

Disadvantage:

1. User cannot specify DNS server for HTTP/TLS traffic.
2. User might not even be aware of this hack, causing confusions. (#1503, #1505, #1507)
3. Only works properly for HTTP/TLS traffic, given that sniparser was implemented correctly (#1876, #1877). If a client uses HTTP/TLS mixed with other traffic, the result will be surprising.
4. If non HTTP/TLS traffic wishes to use this feature, one needs to write their protocol such that it can be identified by sniparser which is not and should not be standardized. (folks at IETF will probably be displeased to see this)

Proposal: Remove sniparser entirely. If this is too radical, add an option and disable it by default.

### PR DESCRIPTION
**Pull request by Mygod**
Fix #2627.

### CODE REVIEW

**Comment by madeye** [comment]
With this change, GFW List and custom list mode won't work again.

So, make sure the submodule is not updated there.

**Comment by Mygod** [comment]
@madeye Are you giving me pressure to implement the changes for GFW list? 🤣

**Comment by madeye** [comment]
Just don't update shadowsocks-libev submodule, then everything should be fine...

**Comment by Mygod** [comment]
Too late. I already started https://github.com/shadowsocks/shadowsocks-android/issues/2452. 😛

**Pull request merged**
