### PR TITLE
Enable kqueue(2) on FreeBSD

### PR DESCRIPTION
**Pull request by eataix**
Reference: http://svnweb.freebsd.org/ports/head/devel/libev/files/patch-ev.c?view=markup

### CODE REVIEW

**Comment by madeye** [comment]
Interesting, have you tested this on FreeBSD already?

**Comment by madeye** [comment]
According to libev's [document](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod), kqueue is broken on all BSDs except NetBSD.

> EVBACKEND_KQUEUE (value 8, most BSD clones)
> Kqueue deserves special mention, as at the time of this writing, it was broken on all BSDs except NetBSD (usually it doesn't work reliably with anything but sockets and pipes, except on Darwin, where of course it's completely useless). Unlike epoll, however, whose brokenness is by design, these  kqueue bugs can (and eventually will) be fixed without API changes to existing programs. For this reason it's not being "auto-detected" unless you explicitly specify it in the flags (i.e. using EVBACKEND_KQUEUE) or libev was compiled on a known-to-be-good (-enough) system like NetBSD.

**Comment by eataix** [comment]
Sure I have tested it (on FreeBSD 10.1-RELEASE).

Before applying this patch, `top(1)` shows that `select(2)` is used:
```
45987 eataix             1  20    0 18748K  3548K select   0:00   0.00% src/ss-server -c /home/eataix/vultr_server.json
```
After applying this patch:
```
43931 eataix             1  20    0 18748K  3596K kqread   0:00   0.00% src/ss-server -c /home/eataix/vultr_server.json
```

It seems that this patch was endorsed by [@delphij](https://www.delphij.net/) according to [this thread on ChinaUnix](http://bbs.chinaunix.net/thread-3678031-1-1.html).

For your reference, `CPython`, `nginx`, and `dnscrypt-proxy` are using kqueue(2) anyway:
```
43839 eataix             1  26    0 96032K 15156K kqread   0:00   0.10% /home/eataix/.pyenv/versions/shadowsocks/bin/python2.7 /home/eataix/.pyenv/versions/shadowsocks/bin/ssserver -c /home/
 9080 www                1  20    0 41912K   904K kqread   0:09   0.00% nginx: worker process (nginx)
96258 _dnscrypt-proxy    1  20    0 25564K   952K kqread   0:01   0.00% /usr/local/sbin/dnscrypt-proxy -a 127.0.0.1:5353 -d -p /var/run/dnscrypt-proxy.pid -l /var/log/dnscrypt-proxy.log -u _
```

**Comment by madeye** [comment]
OK, merged. Thanks!

**Comment by eataix** [comment]
Glad to help.
Thank **_you_** for working on this project. It has served me well. I really appreciate it.

**Pull request merged**
