### PR TITLE
some logical fix in server.c

### PR DESCRIPTION
**Pull request by ptpt52**
1. use remote buf to recv() in server_recv_cb() if remote has beed created
	2. server_recv_cb() should remote_recv_ctx as soon as remote is being created

### CODE REVIEW

**Comment by ptpt52** [comment]
related to https://github.com/shadowsocks/shadowsocks-libev/issues/1455

**Comment by madeye** [comment]
I don't think there is any issue in #1456. Any steps to reproduce your issue?

**Comment by ptpt52** [comment]
yes. no issue in #1456 but need this fix logical

**Comment by ptpt52** [comment]
原来的逻辑认为，remote_send_cb() 被调用后 remote->recv_ctx->io 才被开启，这逻辑上说不通
按道理，remote只要创建了，就可以开始等待接收数据了：ev_io_start(EV_A_ & remote->recv_ctx->io);

**Comment by madeye** [comment]
> 按道理，remote只要创建了，就可以开始等待接收数据了

Actually not, the connection is created but not established yet.

**Comment by ptpt52** [comment]
什么事件会触发 established 状态？

**Comment by madeye** [comment]
When the connection is established, the socket turns to writable. Then you will get a callback from the event loop.

**Comment by madeye** [comment]
Closed due to misunderstanding of the implementation.

**Comment by ptpt52** [comment]
socket 可写了，remote_send_cb()  被调用，如果这个时候 remote->buf->len 不为0呢？

**Comment by madeye** [comment]
> socket 可写了，remote_send_cb() 被调用，如果这个时候 remote->buf->len 不为0呢？

This line: https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L1184

Also read the code here https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L1158. Make sure you understand how connection is checked to be connected.

**Comment by ptpt52** [comment]
but what about this line?
https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L887
and
https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L1043

**Comment by madeye** [comment]
> https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L887

You need to copy the local buffer to remote buffer for further sending in remote_send_cb.

> https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L1043

Ditto.

**Comment by ptpt52** [comment]
如果这一行 https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L887
如果这一行 len > 0 为真
>                 // XXX: should handle buffer carefully
                if (server->buf->len > 0) {

那么当 remote_send_cb 被唤醒的时候，会导致下面这行不会发生

> 
            if (remote->buf->len == 0) {
                server->stage = STAGE_STREAM;

**Comment by madeye** [comment]
> 那么当 remote_send_cb 被唤醒的时候，会导致下面这行不会发生

https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L1216

If buf->len > 0, only if the buffer is sent out, the stage can be changed to STAGE_STREAM.

**Comment by ptpt52** [comment]
好吧
不过，在有数据的情况下，stage要变成 STAGE_STREAM 需要依赖于 remote_send_cb 把第一波数据发完

**Comment by madeye** [comment]
> 不过，在有数据的情况下，stage要变成 STAGE_STREAM 需要依赖于 remote_send_cb 把第一波数据发完

It's expected. And it'd not be a problem.

**Comment by ptpt52** [comment]
我理解的 remote 创建后，就立刻启动 remote_recv_ctx 应该没问题吧？
server 被连接后，也立刻启动 server_recv_ctx

然后
我理解 server_send_ctx 被唤醒是在 remote_recv_ctx 收到数据后
remote_send_ctx 被唤醒是在 server_recv_ctx 收到有效数据后

^_^.

**Comment by ptpt52** [comment]
我做了测试／调试打印，结果和我的预期是一样的

> change to STAGE_STREAM in remote_send_cb len=0
> change to STAGE_STREAM in remote_send_cb len=0
> change to STAGE_STREAM in remote_recv_cb    <----this happened when use telnet x.x.x.x 22
> change to STAGE_STREAM in remote_send_cb len=0
> change to STAGE_STREAM in remote_send_cb len=0
> change to STAGE_STREAM in remote_send_cb len=0

**Comment by madeye** [comment]
> 我理解的 remote 创建后，就立刻启动 remote_recv_ctx 应该没问题吧？

Nope, remote_recv_ctx should be only started after the connection established, not created.

> server 被连接后，也立刻启动 server_recv_ctx

It's already done in accept_cb.

> 我理解 server_send_ctx 被唤醒是在 remote_recv_ctx 收到数据后

Incorrect. Only if there is data that cannot be sent from remote_recv_cb, we will stop remote_recv and start server_send.

> remote_send_ctx 被唤醒是在 server_recv_ctx 收到有效数据后

Ditto.

I suggest you read the code again to avoid all these misunderstandings, especially the part how async I/O works.

One biggest question you should ask yourself is if your assumptions were right, shadowsocks-libev would be not usable from the very beginning.

**Pull request closed without merging**
