### PR TITLE
fixed: remove color log

### PR DESCRIPTION
**Pull request by kimw**

### CODE REVIEW

**Comment by wongsyrone** [comment]
Any reason?

**Comment by madeye** [comment]
@wongsyrone `USE_TTY()` is able to auto-detect the TTY settings.

**Comment by kimw** [comment]
@wongsyrone After the change, logs will be colored in TTY still, but not logfile.

**Comment by wongsyrone** [comment]
I see.

**Comment by kimw** [comment]
FYI
untitled

**Pull request merged**
