### PR TITLE
Upgrade PCRE to PCRE2

### PR DESCRIPTION
**Pull request by wongsyrone**
NOTE: only compile tested, please test before merging.

- Use 8bit variant by default

Signed-off-by: Syrone Wong <wong.syrone@gmail.com>

### CODE REVIEW

**Comment by wongsyrone** [comment]
Ubuntu 14.04 on Travis CI sucks, I give up.

**Comment by kimw** [comment]
You lier. You said give up. Never trust you any more.

**Comment by wongsyrone** [comment]
LUL, I don't want to touch the CI anymore since they are using outdated packages instead of the code.

**Comment by kimw** [comment]
Sometimes I don't believe that  the CI have the ability to save my time.

**Comment by madeye** [comment]
pcre2 is a "new" package added in 16.04. I suggest not to upgrade this dependency as it won't improve anything but causing confusion.

**Comment by madeye** [comment]
Closed for now. Let's merge it in after April 2019.

**Comment by david-geiger** [comment]
Is this project dead? and replaced with shadowsocks-rust?

Otherwise I think it is time to port it to pcre2 as some distributions, like us Mageia Linux, started to drop old pce library.

Regards,
David

**Pull request closed without merging**
