### PR TITLE
Use chacha20-ietf as a default cipher instead of rc4-md5

### PR DESCRIPTION
**Pull request by YegorIevlev**

### CODE REVIEW

**Comment by YegorIevlev** [comment]
Thanks!

**Comment by madeye** [comment]
At the very beginning, shadowsocks only accepts three ciphers, table, rc4 and rc4-md5.

**Comment by YegorIevlev** [comment]
@madeye AES and SHA-256 already existed in 2013, why did shadowsocks not use them?

**Comment by YegorIevlev** [comment]
Ironically, the most secure ciphers now are also the fastest ones. I obviously meant ChaCha20-Poly1305.

**Comment by madeye** [comment]
It depends. https://github.com/shadowsocks/shadowsocks-libev/issues/1242#issuecomment-279325242

Currently, I think it's safe to use chacha20-poly1305 as default cipher.

**Pull request merged**
