### PR TITLE
Check port before add port via ss-manager

### PR DESCRIPTION
**Pull request by GhostFlying**
1. ss-manager will try to bind needed port to check its availability;

2. echo "ok" to normal request;

3. echo "port is not available" back when port used by other process.

I am not so farmiliar with pure c and libev, please point out anything improper and I will fix it soon.

### CODE REVIEW

**Comment by madeye** [comment]
Cool! The code looks quite good.

Merged, thanks!

**Comment by junsen** [comment]
make[1]: Entering directory `/tmp/shadowsocks-libev/src'
  CC       ss_manager-manager.o
cc1: warnings being treated as errors
manager.c: In function 'create_and_bind':
manager.c:322: error: 'is_port_reuse' may be used uninitialized in this function
manager.c:322: error: 'listen_sock' may be used uninitialized in this function

**Comment by GhostFlying** [comment]
@junsen can u provide more info abount this? I can not reproduce this.

But actually I find there may be an issue here and I will fix it.

**Comment by kdrx** [comment]
@junsen
I get the same issue, you can add -Wno-uninitialized to your compile option or initialize the uninitialized variables to get rid of the error.

**Pull request merged**
