### PR TITLE
Sync debian/ folder with debian release 3.1.1+ds-1~exp1

### PR DESCRIPTION
**Pull request by rogers0**

### CODE REVIEW

**Comment by debiansid** [comment]
simple-obfs is still 0.0.3 in debian package release

**Comment by rogers0** [comment]
@debiansid 0.0.5-1 is in unstable since last week

**Comment by debiansid** [comment]
@rogers0 thank you Sir.

**Comment by rogers0** [comment]
@debiansid no problem.
but simple-obfs packaging is not in ideal status still.
e.g. https://bugs.debian.org/874616
so it'd be appreciated if you you can help.

**Pull request merged**
