### PR TITLE
Update local.c

### PR DESCRIPTION
**Pull request by kimw**
Setup default cipher instead of null

---

Before,

```bash
$ ss-local -s::1 -p8388 -l1080 -k123456 -v
 2016-10-25 19:46:44 INFO: initializing ciphers... (null)
 ...
```

After,

```bash
$ ss-local -s::1 -p8388 -l1080 -k123456 -v
 2016-10-25 19:46:58 INFO: initializing ciphers... table
 ...
```

### CODE REVIEW

**Comment by Mygod** [comment]
Using a safe method as default would be better.

**Comment by wongsyrone** [comment]
Agreed. How about rc4-md5.

**Comment by madeye** [comment]
Fixed via 85a5c866372ab69fb4ebf06e470e9ce0f3fd0216

**Comment by kimw** [comment]
@Mygod, Yap, I know, the `table` is definitely not a good choice. In fact I never ever use it.

It was chosen because it was documented as the default cipher. Maybe it's a good time to make some change now.

I'm confusing on which one should be the best one. As I known, the `rc4-md5`, `aes-256-cfb`, `camellia-256-cfb`, and `chacha20` are favored by most people. It's to hard to pick out one from them.

@wongsyrone, Why not `chacha20`? I'm not good at encryption. Is rc4-md5 kinda same as chacha20? And, why not `ase-256-cfb` as it's the default one in shadowsocks-android?

**Comment by wongsyrone** [comment]
Another way is to remove deprecated ciphers from codebase completely.

**Comment by kimw** [comment]
@Mygod @wongsyrone  OK, as in the last commit 83c244bc9a0f80096822a302504bbc3fb8ed6315, both the codes and docs are defaulted to `rc4-md5`. @madeye is a fasty guy as he used be ;-p

**Comment by kimw** [comment]
> @wongsyrone 
> Another way is to remove deprecated ciphers from codebase completely.

Totally agree.

**Comment by kimw** [comment]
`rc4` & `table` should be removed.

**Comment by madeye** [comment]
I don't think so.

As shadowsocks-libev is designed for low-end boxes and embedded devices. Table / RC4 is still very useful. Especially the table cipher, we could consider it as non-encrypt mode of shadowsocks.

BTW, the default cipher is rc4-md5 now.

**Pull request merged**
