### PR TITLE
fix and update scripts to generate rpms

### PR DESCRIPTION
**Pull request by was4444**

### CODE REVIEW

**Comment by madeye** [comment]
@librehat Please help to review this PR. Thanks!

**Comment by librehat** [comment]
The previous commits made by me deleted rpm-specific service files, in favour of debian's. I suggest you modify debian files. RPM should be kept in accordance with DEB.

**Comment by was4444** [comment]
Hi @librehat,
I will never modify the debian files as long as I do not have a debian/ubuntu system.
And even if I modified them, I still prefer keeping a copy in the rpm/SOURCES directory, as not all versions contains the all related files.
And the current shadowsocks-libev can not generate a RPM on my sl7.

**Comment by librehat** [comment]
@was4444 Using debian files keeps consistency between RPM-based distributions and Debian variants. As for other versions, I'm afriad they're not back-compatible (there is no need to do so as one could download released tar balls).

I haven't tested the `genrpm.sh` yet, but the SPEC file is tested on my Fedora 22 box. Please submit another pull request for `genrpm.sh` if there are errors. And please, do not submit new services files into RPM dir (you can find the source files in debian dir since I specified them clearly in SPEC file).

**Comment by was4444** [comment]
Hi @librehat,

The shadowsocks-libev.service(only the server part, a local part may be useful) can only be found in debian directory since [v2.3.3](643d579bdf9591c7fd4af4d39c14305a16437cf1). So we only support the versions after that? Ok, the latest is better.

If the SPEC file now works well, you can simply remove the `genrpm.sh`, there's no need to fix it as no one else use or need it.

**Comment by was4444** [comment]
Some service files from https://aur.archlinux.org/packages/shadowsocks-libev/ may be useful.
```
shadowsocks-libev-redir@.service
shadowsocks-libev-server@.service
shadowsocks-libev-tunnel@.service
shadowsocks-libev@.service
```

**Pull request closed without merging**
