### PR TITLE
udprelay: exclude udp remote_recv_sendto buff full

### PR DESCRIPTION
**Pull request by babarosaM33**

### CODE REVIEW

**Comment by madeye** [comment]
Nope, you should not do that. UDP relay is implemented as a best effort packet forwarder, as UDP itself is not a reliable protocol.

**Comment by babarosaM33** [comment]
@madeye 
i encounter a lot of remote recv sendto error  in system log. most of them caused by eagain.
 btw, this patch just silence these error logs.

**Comment by babarosaM33** [comment]
@madeye 

eagain indicates this socket is busy.

without reset timer, program would terminate this socket after timeout.

**Comment by madeye** [comment]
No, it's not a good idea to silent this error.

When you seeing a lot of EAGAN on your UDP socket, it's probably caused by  misconfigured kernel parameters.

To enlarge the default and max sending buffer (WMEN) size, you can follow this guide: https://www.cyberciti.biz/faq/linux-tcp-tuning/

**Comment by babarosaM33** [comment]
@madeye

but the current program would terminate a busy socket when timeout alarmed. i don't thinke this routine make sense.

**Comment by madeye** [comment]
The possibility is almost zero, as we have a min timeout for UDP relay: https://github.com/shadowsocks/shadowsocks-libev/blob/22d5e599726d44fa06b0f9970906076f0f33bde1/src/jconf.h#L31

Typically, if there're packets keep coming, we would not kill any busy socket, unless the kernel keeps busy for seconds, which is likely a system hang.

But I agree we can trigger the timer, to avoid any confusion.

**Pull request merged**
