### PR TITLE
Allow long direct TCP connections

### PR DESCRIPTION
**Pull request by Mygod**
Fixes https://github.com/shadowsocks/shadowsocks-android/issues/2078.

### CODE REVIEW

**Comment by Mygod** [comment]
Maybe we should just do this for all connections?

**Comment by madeye** [comment]
Let's just apply it for direct connections.

I still believe any connection that not send any packet in 600s should be closed.

**Comment by Mygod** [comment]
I think it's widely used for pushing notifications...

**Comment by madeye** [comment]
Okay, just keep timeout in `ss-server`. 7ad2df9

**Pull request merged**
