### PR TITLE
Add AEAD support

### PR DESCRIPTION
**Pull request by madeye**
More details can be found here: https://github.com/shadowsocks/shadowsocks-org/issues/30

### CODE REVIEW

**Comment by Mygod** [comment]
Looks like we need to install `libmbedtls-dev` as well.

**Comment by Mygod** [comment]
Got this on `ss-local`: `ERROR: Cannot set mbed TLS cipher key`. Seems to work fine on ss-server.

Also I can't seem to pass configuration directly to ss-local via arguments. Only works via config json.

**Comment by wongsyrone** [comment]
It is caused by incorrect key len

cipher_ctx->cipher->key_len is always 16 for aes-192/256-gcm, aes-128-gcm works fine.

**Comment by wongsyrone** [comment]
2017-01-31 15:40:31 INFO: initializing ciphers... aes-192-gcm
 2017-01-31 15:40:31 INFO: tcp port reuse enabled
 2017-01-31 15:40:31 INFO: udprelay enabled
 2017-01-31 15:40:31 INFO: udp port reuse enabled
 2017-01-31 15:40:31 INFO: listening at 127.0.0.1:1080
 2017-01-31 15:40:55 INFO: method: 1
 2017-01-31 15:40:55 INFO: key len: 16
 2017-01-31 15:40:55 ERROR: setkey ret: 0xffff9f00
 2017-01-31 15:40:55 ERROR: Cannot set mbed TLS cipher key

 2017-01-31 15:41:53 INFO: initializing ciphers... aes-256-gcm
 2017-01-31 15:41:53 INFO: tcp port reuse enabled
 2017-01-31 15:41:53 INFO: udprelay enabled
 2017-01-31 15:41:53 INFO: udp port reuse enabled
 2017-01-31 15:41:53 INFO: listening at 127.0.0.1:1080
 2017-01-31 15:41:56 INFO: method: 2
 2017-01-31 15:41:56 INFO: key len: 16
 2017-01-31 15:41:56 ERROR: setkey ret: 0xffff9f00
 2017-01-31 15:41:56 ERROR: Cannot set mbed TLS cipher key

**Comment by wongsyrone** [comment]
The most weird thing is all working well when testing on local host, but won't work when client is on ARM router and server on x64.

server log:
2017-01-31 03:46:14 INFO: accept a connection
2017-01-31 03:46:14 INFO: connect to xxx:5228
2017-01-31 03:46:14 INFO: remote connected
2017-01-31 03:46:15 INFO: accept a connection
2017-01-31 03:46:15 INFO: connect to xxx:443
2017-01-31 03:46:15 INFO: remote connected
2017-01-31 03:46:15 INFO: remote_recv close the connection
2017-01-31 03:46:15 INFO: current remote connection: 1
2017-01-31 03:46:15 INFO: current server connection: 1
2017-01-31 03:46:15 INFO: accept a connection
2017-01-31 03:46:15 INFO: connect to xxx:443
2017-01-31 03:46:15 INFO: remote connected
2017-01-31 03:46:15 INFO: remote_recv close the connection
2017-01-31 03:46:15 INFO: current remote connection: 1
2017-01-31 03:46:15 INFO: current server connection: 1
2017-01-31 03:46:20 INFO: accept a connection
2017-01-31 03:46:20 INFO: connect to xxx:443
2017-01-31 03:46:21 INFO: remote connected
2017-01-31 03:46:21 INFO: remote_recv close the connection
2017-01-31 03:46:21 INFO: current remote connection: 1
2017-01-31 03:46:21 INFO: current server connection: 1
2017-01-31 03:46:21 INFO: accept a connection
2017-01-31 03:46:21 INFO: connect to xxx:443
2017-01-31 03:46:21 INFO: remote connected
2017-01-31 03:46:21 INFO: accept a connection
2017-01-31 03:46:21 INFO: connect to xxx:443
2017-01-31 03:46:21 INFO: remote_recv close the connection
2017-01-31 03:46:21 INFO: current remote connection: 2
2017-01-31 03:46:21 INFO: current server connection: 2
2017-01-31 03:46:21 INFO: remote connected
2017-01-31 03:46:21 INFO: remote_recv close the connection
2017-01-31 03:46:21 INFO: current remote connection: 1
2017-01-31 03:46:21 INFO: current server connection: 1

**Comment by madeye** [comment]
@wongsyrone 

1. What's the endian of your router?
2. Are you using `ss-redir` or `ss-local`?

**Comment by wongsyrone** [comment]
Linksys WRT1900AC v1

1. I think it is little-endian, not sure about it
2. ss-local + redsocks + iptables nat + ipset

processor       : 0
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 25.00
Features        : half thumb fastmult vfp edsp vfpv3 tls idiva idivt vfpd32 lpae 
CPU implementer : 0x56
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x584
CPU revision    : 2

processor       : 1
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 25.00
Features        : half thumb fastmult vfp edsp vfpv3 tls idiva idivt vfpd32 lpae 
CPU implementer : 0x56
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x584
CPU revision    : 2

Hardware        : Marvell Armada 370/XP (Device Tree)
Revision        : 0000
Serial          : 0000000000000000

**Comment by madeye** [comment]
Please try 05d5121.

**Comment by Mygod** [comment]
It's working on my side.

**Comment by Mygod** [comment]
But also I'm observing intermittent `ERROR: failed to handshake with <IP>` no matter I use stream cipher or AEAD.

**Comment by wongsyrone** [comment]
Good job. It's working now. I will do more tests.

**Comment by Mygod** [comment]
Interestingly the intermittent `failed to handshake` only occurs 90s after the `ss-server` starts.

**Comment by madeye** [comment]
@Mygod With `-v`, is there a timeout log before `failed to handshake`?

**Comment by Mygod** [comment]
Hmm yeah there is a `TCP connection timeout`. But my timeout is set to 60s.

**Comment by madeye** [comment]
@Mygod Please try this commit: 790520c.

**Comment by Mygod** [comment]
Okay no more errors! Btw I suggest that we should output more information to `report_addr` for easier debugging.

**Comment by wongsyrone** [comment]
How about adding err level as well?

**Comment by madeye** [comment]
@Mygod @wongsyrone Pull requests are welcome. 😄

**Comment by wongsyrone** [comment]
If no critical issues are found, I think this can be merged after one week.

**Comment by Mygod** [comment]
Why wait?

**Comment by madeye** [comment]
@wongsyrone Please help to finalize the documents in SIP004. And please make sure all the contributors are properly mentioned in the text...

**Pull request merged**
