### PR TITLE
resolve domain so we can bypass domain with geoip

### PR DESCRIPTION
**Pull request by blackgear**
Many users wants to do bypass with geoip:
https://github.com/shadowsocks/shadowsocks-libev/issues/78
https://github.com/shadowsocks/shadowsocks-libev/issues/564

So users are limited to Firefox and some few apps that using a local resolve.
But if we can resolve the domain then the geoip works for all situations.

This can be recognized as a user-behavior-leak but only users who using ACL will be affected, but it truly helps people who want a easier way to balance speed and traffic.
Maybe at least we can add an option to enable this.

### CODE REVIEW

**Comment by madeye** [comment]
Nope, you shouldn't do that. It's not a unblocking API.

**Comment by blackgear** [comment]
So maybe I should rewrite a udns version to do that?

**Comment by madeye** [comment]
If so, you should also solve DNS pollution. In other words, resolving hostnames locally is not a good idea.

**Comment by blackgear** [comment]
According to our ACL logic, we do acl_match_host(host) first and then acl_match_host(ip), so we just need to add the polluted domains to the proxy list.

```
[bypass_all]

[proxy_list]
# Polluted Domains
(^|\.)google(\.(?!-)[a-zA-Z0-9-]{1,63}(?<!-)){1,2}$

# Foreign IPs
1.0.0.0/24
....
```

Then google will be alway proxy.

Besides, a user who discovered this ACL feature must be a power user, I think they can make a local clean DNS....

**Comment by madeye** [comment]
It looks doable. Merged for now.

Thanks!

**Comment by lixingcong** [comment]
Here is Daniel's ACL usage

https://darknode.in/network/geoip-proxy-acl/

**Pull request merged**
