### PR TITLE
Support priority for name resolving

### PR DESCRIPTION
**Pull request by hghwng**

### CODE REVIEW

**Comment by madeye** [comment]
Sorry, I choose to not merge this change.

**Comment by hghwng** [comment]
#531 and #406 can be fixed if name resolving priority is supported. Could you please explain the reason for not merging?

**Comment by kimw** [comment]
I'm interesting on the reason too.

**Comment by Mygod** [comment]
@hghwng @kimw See https://github.com/shadowsocks/shadowsocks-libev/commit/72ee77ea35c83017af4426775f59021692850769.

**Comment by kimw** [comment]
@Mygod 
In fact, I just wanna talk more about what's the reason that made the decision to not support priority for name resolving, but not the feature.

**Pull request closed without merging**
