### PR TITLE
OS X 10.11 上的 fastopen

### PR DESCRIPTION
**Pull request by crvv**
Python 的我这里也搞好了，但是一方面不清楚 Python 版 ss 的维护情况，另一方面不确定用 C 扩展合不合适
总之代码在：
https://github.com/crvv/tcp_fastopen_darwin
https://github.com/crvv/shadowsocks

### CODE REVIEW

**Comment by crvv** [comment]
补充一下，setsockopt TCP_FASTOPEN 的参数，参考 https://tools.ietf.org/html/rfc7413 来看，我觉得没必要设 5，而 Darwin 又只支持设 1，我就改成 1 了

**Comment by madeye** [comment]
Merged, thanks!

**Comment by madeye** [comment]
You can also open a pull request to https://github.com/shadowsocks/shadowsocks (master branch), the maintainer would merge your pull requset then.

**Comment by madeye** [comment]
Have you tested it already? I tried it on localhost, but it didn't work. Any suggestion?

**Comment by crvv** [comment]
I tested on OS X 10.11. I haven't test it on Linux.
`ss-server -s localhost` or `ss-server -s ::1` doesn't work, and this error is not related with my commit. Shadowsocks-libev I installed from homebrew alse has this issue.
`ss-server -s 127.0.0.1` work

**Pull request merged**
