### PR TITLE
add docker image

### PR DESCRIPTION
**Pull request by Secbone**

### CODE REVIEW

**Comment by wongsyrone** [comment]
The folder name `ss-libev` is not accurate, I think you'd better write something to distinguish it from the existing image, `alpine`.

**Comment by madeye** [comment]
We already have a Alpine based docker image: https://github.com/shadowsocks/shadowsocks-libev/blob/master/docker/alpine/Dockerfile

Anyway, thanks for your pull request.

**Comment by wongsyrone** [comment]
In my opinion, something like `alpine-tiny` would be better.

**Comment by wwl1234** [comment]
你好不知道你能不能看懂中文 我现在想用java来写android的 但是ss-local 在connect的时候一直连接失败 不知道什么原因导致的 TCP connect time out 在local.c server_recv_cb方法中     if (!fast_open || remote->direct) {
                    // connecting, wait until connected
                    int r = connect(remote->fd, (struct sockaddr *)&(remote->addr), remote->addr_len);

                    if (r < 0 && errno != EINPROGRESS) {
                        ERROR("connect");
                        close_and_free_remote(EV_A_ remote);
                        close_and_free_server(EV_A_ server);
                        return;
                    }

                    if (r == 0) {
                        if (verbose) LOGI("connected immediately");
                        remote_send_cb(EV_A_ & remote->send_ctx->io, 0);
                    } else {
                        // wait on remote connected event
                        ev_io_stop(EV_A_ & server_recv_ctx->io);
                        ev_io_start(EV_A_ & remote->send_ctx->io);
                        ev_timer_start(EV_A_ & remote->send_ctx->watcher);
                    }


in loca.c function server_recv_cb connect(remote->fd, (struct sockaddr *)&(remote->addr), remote->addr_len); always wait i do not know why can you help me thank you

**Pull request closed without merging**
