### PR TITLE
更新依赖，且Arch应直接安装udns libev

### PR DESCRIPTION
**Pull request by Sherlock-Holo**

### CODE REVIEW

**Comment by debiansid** [comment]
Arch应该编译软件包更方便吧

**Comment by Sherlock-Holo** [comment]
按照一般用户来说是的，但是如果有些已经用了编译安装来说，这样也可以提供安装/更新的办法

**Comment by debiansid** [comment]
Alpine linux做路由的话 另外做个编译机 路由上尽量少装软件

**Comment by debiansid** [comment]
When we can build ss-libev with libressl on alpine Linux 

NEW FEATURES AND NOTEWORTHY CHANGES

Switch from OpenSSL to LibreSSL
Support for aarch64 (uboot only for now)
Support for ZFS as root
PostgreSQL update to 9.6.x. See the PostgreSQL documentation for upgrade instructions
Samba 4.5.3
GTK+3.0 3.22.5
glib 2.50.2
Support for R, JRuby and OCaml
Better python3 support
The nodejs package was renamed to nodejs-current and moved to the community repository. The nodejs-lts package was renamed to nodejs. This means that you get the LTS version if you do apk add nodejs.

**Pull request merged**
